import Head from 'next/head'
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
import { Inter } from '@next/font/google'
import { Dashboard } from 'pages/dashboard/Dashboard';
import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
import { RPC_ENDPOINT, ENVIRONMENT } from "utils/config";
import {
  BraveWalletAdapter,
  CoinbaseWalletAdapter,
  PhantomWalletAdapter,
  SolflareWalletAdapter,
} from '@solana/wallet-adapter-wallets';

import styles from '../styles/Home.module.css'
import { useEffect, useMemo } from 'react';
import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
import { StoreProvider } from './useStore';
require("@solana/wallet-adapter-react-ui/styles.css");

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const network = ENVIRONMENT as WalletAdapterNetwork;

  const phantom = new PhantomWalletAdapter();
  const solflare = new SolflareWalletAdapter({ network });
  const coinbase = new CoinbaseWalletAdapter();
  const brave = new BraveWalletAdapter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <ConnectionProvider endpoint={RPC_ENDPOINT.endpoint}>
            <WalletProvider wallets={[
phantom,
solflare,
coinbase,
brave,
            ]} autoConnect>
                <WalletModalProvider>
                  <StoreProvider>
                    <Dashboard/>
                  </StoreProvider>
                </WalletModalProvider>
            </WalletProvider>
        </ConnectionProvider>
    </>
  )
}
